services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./backend:/app/backend
      - "./EquiTie - Senior Software Engineer - Case Study/data:/app/data"
      - ./.env:/app/.env
    env_file:
      - ./.env
    environment:
      - ENVIRONMENT=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3
